feature/title
superbowl-alex/crew-team-project pull request #1
Opened 2022-05-26 19:55 UTC by ValeriiaMezentseva

add title and pre-title base

2022-05-26 20:27 UTC, superbowl-alex requested changes

2022-05-26 20:27 UTC, superbowl-alex commented on src/sass/_base.scss
> +  line-height: 1.16;
В мене вийшло 1,17

2022-05-26 20:27 UTC, superbowl-alex commented on src/sass/_base.scss
> +  color: #ffa5ba;
Завтра в першій половині дня додам змінні кольорів. Виправ, будь-ласка

2022-05-26 20:27 UTC, superbowl-alex commented on src/sass/_base.scss
> +    line-height: 1.14;
1,15

2022-05-26 20:27 UTC, superbowl-alex commented on src/sass/_base.scss
> +    font-size: 58px;
В цьому медіа вже 1,14

2022-05-27 11:18 UTC, ValeriiaMezentseva commented on src/sass/_base.scss
> +  line-height: 1.16;
виправлено

2022-05-27 11:18 UTC, ValeriiaMezentseva commented on src/sass/_base.scss
> +    line-height: 1.14;
виправлено

2022-05-27 11:18 UTC, ValeriiaMezentseva commented on src/sass/_base.scss
> +    font-size: 58px;
виправлено

2022-05-27 11:18 UTC, ValeriiaMezentseva commented on src/sass/_base.scss
> +  color: #ffa5ba;
змінних ще немає, якщо правильно розумію

2022-05-27 12:26 UTC, closed without merging