feature/advantages
superbowl-alex/crew-team-project pull request #20
Opened 2022-05-28 09:34 UTC by ValeriiaMezentseva

adding advantages section

2022-05-28 12:28 UTC, zarozhenya requested changes

2022-05-28 12:28 UTC, zarozhenya commented on src/partials/advantages.html
> +  <div class="adv-container">
у нас вже прописані стилі для контейнера, можете просто використовувати клас container

2022-05-28 12:28 UTC, zarozhenya commented on src/partials/advantages.html
> +<section id="advantages" class="section section--background">
мені здаєтьс краще просто творювати не кллас-модифікатор section--background, а просто за назвою секції (advantages). Бо можливо в іншоіу мтсці доведеться використовувати модифікатор класу з таким же ім'ям, а він вже буде зайнятий

2022-05-28 12:28 UTC, zarozhenya commented on src/sass/_advantages.scss
> +.adv-container {
стилі для контейнера вже прописані були у нас

2022-05-28 12:28 UTC, zarozhenya commented on src/sass/_advantages.scss
> +.advantages {
стилі для списків вже скидались, тому тут йде дублювання маржину, падінгу та list-style

2022-05-28 12:28 UTC, zarozhenya commented on src/sass/_advantages.scss
> +  font-family: 'Titan One';
тут також стилі вже були прописані, просто напишіть додактовий клас title  урозмітці

2022-05-29 06:27 UTC, superbowl-alex approved these changes

2022-05-29 06:28 UTC, superbowl-alex approved these changes

2022-05-29 06:34 UTC, zarozhenya approved these changes

2022-05-29 06:34 UTC, merged